apiVersion: v2
name: karpenter-bundle
description: A Helm chart bundle that deploys Karpenter with AWS Crossplane resources (IAM roles, SQS queues, CloudWatch rules).
version: ""
appVersion: 1.5.0
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
  - bundle
  - crossplane
home: https://github.com/giantswarm/karpenter-app
icon: https://s.giantswarm.io/app-icons/karpenter/1/light.svg
sources:
  - https://github.com/aws/karpenter/
  - https://karpenter.sh/
annotations:
  io.giantswarm.application.team: phoenix
maintainers:
  - name: giantswarm/team-phoenix
    email: team-phoenix@giantswarm.io
