apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: [[ .Version ]]
appVersion: 0.29.2
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://karpenter.sh/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/aws/karpenter/
annotations:
  application.giantswarm.io/team: phoenix
dependencies:
  - name: karpenter
    version: v0.29.2
    repository: oci://public.ecr.aws/karpenter
maintainers:
  - name: giantswarm/team-phoenix
    email: team-phoenix@giantswarm.io
