apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: [[ .Version ]]
appVersion: 0.29.2
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://github.com/giantswarm/karpenter-app
icon: https://s.giantswarm.io/app-icons/karpenter/1/light.svg
sources:
  - https://github.com/aws/karpenter/
  - https://karpenter.sh/
annotations:
  application.giantswarm.io/team: phoenix
dependencies:
  - name: karpenter
    version: v0.32.0
    repository: oci://public.ecr.aws/karpenter
maintainers:
  - name: giantswarm/team-phoenix
    email: team-phoenix@giantswarm.io
